"""Add 'is_confirmed' to alumni fields

Revision ID: 2fb238c3cdf8
Revises: 
Create Date: 2020-10-23 23:54:47.690673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb238c3cdf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'is_confirmed')
    # ### end Alembic commands ###
