"""Add 'is_confirmed' to alumni fields

Revision ID: e55137d1b609
Revises: 2fb238c3cdf8
Create Date: 2020-10-24 00:01:43.007041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55137d1b609'
down_revision = '2fb238c3cdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni', 'is_confirmed')
    # ### end Alembic commands ###
